# coding: utf-8

"""
    Agent Protocol

    Specification of the API protocol for communication with an agent.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictInt


class Pagination(BaseModel):
    """
    Pagination
    """

    total_items: StrictInt = Field(..., description="Total number of items.")
    total_pages: StrictInt = Field(..., description="Total number of pages.")
    current_page: StrictInt = Field(..., description="Current_page page number.")
    page_size: StrictInt = Field(..., description="Number of items per page.")
    __properties = ["total_items", "total_pages", "current_page", "page_size"]

    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)
    """Pydantic configuration"""

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Pagination:
        """Create an instance of Pagination from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Pagination:
        """Create an instance of Pagination from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Pagination.model_validate(obj)

        _obj = Pagination.model_validate(
            {
                "total_items": obj.get("total_items"),
                "total_pages": obj.get("total_pages"),
                "current_page": obj.get("current_page"),
                "page_size": obj.get("page_size"),
            }
        )
        return _obj
