# coding: utf-8

"""
    Agent Protocol

    Specification of the API protocol for communication with an agent.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field, StrictStr


class TaskRequestBody(BaseModel):
    """
    Body of the task request.  # noqa: E501
    """

    input: Optional[StrictStr] = Field(None, description="Input prompt for the task.")
    additional_input: Optional[Dict[str, Any]] = Field(
        None, description="Input parameters for the task. Any value is allowed."
    )
    __properties = ["input", "additional_input"]

    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)
    """Pydantic configuration"""

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TaskRequestBody:
        """Create an instance of TaskRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True, exclude={}, exclude_none=True)
        # set to None if input (nullable) is None
        # and model_fields_set contains the field
        if self.input is None and "input" in self.model_fields_set:
            _dict["input"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TaskRequestBody:
        """Create an instance of TaskRequestBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TaskRequestBody.model_validate(obj)

        _obj = TaskRequestBody.model_validate(
            {"input": obj.get("input"), "additional_input": obj.get("additional_input")}
        )
        return _obj
