[tool.poetry]
name = "agent-protocol-client"
version = "1.2.0"
description = "Agent Communication Protocol Client"
authors = ["AI Engineers Foundation <aiengineersfoundation@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://agentprotocol.ai/"
repository = "https://github.com/AI-Engineers-Foundation/agent-protocol/tree/main/packages/client/python"
packages = [{ include = "agent_protocol_client" }]

[tool.poetry.dependencies]
python = "^3.7"

aiohttp = "^3.8.4"
pydantic = "^2.0.0"
python-dateutil = "^2.8.2"
urllib3 = "^1.25.3"

[tool.poetry.group.dev.dependencies]
isort = "^5.0.0"
ruff = ">=0.5.0,<1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/AI-Engineers-Foundation/agent-protocol/issues"
